package exceptions;

public class ExceptionDay {

	public static void main(String[] args) {

		try {
			int a = 60 / 3;
			System.out.println(a);

			int[] aray = new int[4];
			aray[0] = 5;
			aray[1] = 5;
			aray[2] = 5;
			aray[3] = 5;
			aray[4] = 5;// this is out of bound array because we have only 4 arrays and we are trying to
						// fit 5
			System.out.println(aray[3]);
			String b = "Exceptions are fun!!";
			System.out.println(b.length());

		} catch (ArithmeticException e) {
			System.out.println("You're trying to devide by Zero!!");
			System.out.println(e);// to show the location of the error
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("The array size is Smaller.");
			System.out.println(e);// to print out the exact location of error
		} catch (Exception e) { // this should always be in the bottom. we user this when we dont know which
								// subclass of exception class is it coming from.
			System.out.println("This error was generated by Exception.");
		} finally {
			System.out.println("This code is printing from finally block!!! YAYAYAYAYAYA ");
		}

		System.out.println("This statement is coming from Fahim Paikar outside the try and catch block.");
	}

}
